[versions]
junit = "5.10.2"
vavr = "1.0.0-alpha-4"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
vavr = { module = "io.vavr:vavr", version.ref = "vavr"}

[plugins]


